In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../pak_election_data_cleaned_20180124.csv')

/Users/zohaib/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2723: DtypeWarning: Columns (61) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
df.head()

,id_no,na,na_value,na_name,sr,candidate_name,party,party1,party_93,nnparty,...,winner,ndivision,nzones_20,nregions_12,nregions_11,nprov,party_2013,id_respondent,n_registerd,ap1
0,43.0,NaN,13,Na-13 Abbottabad-II,5.0,Mr.Mohammad Azam Khan,IND,39.0,NaN,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10119,2,1
1,5201.0,1.0,1,NA-1 PESHAWAR-I,1.0,Haji Dost Mohammad,IND,138.0,102.0,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,3,1
2,5307.0,NaN,22,"NA-22 SWAT-II, Old Swat-III",3.0,Mr. Abdul Jabbar Khan,IND,39.0,39.0,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,107,3,1
3,719.0,195.0,195,NA-195 Quetta-II,1.0,Mr.Abdul Wahid,IND,39.0,NaN,88.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10794,2,1
4,108.0,NaN,18,NW-18 Dir,6.0,Majidullah,Independent,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10913,3,1

In [5]:
df_meta = pd.read_csv('../map_attributes_2002_2008_2013.csv')

In [6]:
df_meta.head()

,year,na_number,na_value,na_name,winner,winner_party,runnerup,runnerup_party,victory_margin,turn_out,winner_party_cat,runnerup_party_cat
0,2002,NA-1,1,NA-1 PESHAWAR-I,Mr.Shabir Ahmad,Muttahidda Majlis-e-Amal Pakistan,Mr.Usman Bashir Bilour,Awami National Party,21.098610,28.726802,Muttahidda Majlis-e-Amal Pakistan,Awami National Party
1,2002,NA-10,10,NA-10 Mardan-II,Maulana Muhammad Qasim,Muttahidda Majlis-e-Amal Pakistan,Mr.Rahim Dad Khan,Pakistan Peoples Party Parliamentarians,61.725426,39.945134,Muttahidda Majlis-e-Amal Pakistan,Pakistan Peoples Party Parliamentarians
2,2002,NA-100,100,NA-100 Gujranwala-VI,Chaudhry Bilal Ijaz,Pakistan Muslim League (Q),Mr.Hamed Naser Chattha,Pakistan Muslim League (J),17.224894,49.322182,Pakistan Muslim League (Q),Other
3,2002,NA-101,101,NA-101 Gujranwala-VII,Mr.Hamid Nasir Chatta,Pakistan Muslim League (J),Mr.Asma Shah Nawaz,Pakistan Peoples Party Parliamentarians,3.238344,4.920156,Other,Pakistan Peoples Party Parliamentarians
4,2002,NA-102,102,NA-102 Hafizabad-I,Chaudhry Mehdi Hasan Bhatti,Pakistan Muslim League (Q),Brig ВЁ Muhammad Usman Tarar,Pakistan Muslim League (N),6.626359,51.783346,Pakistan Muslim League (Q),Pakistan Muslim League (N)

In [8]:
df_meta.groupby('year').describe()

              na_value     turn_out  victory_margin
year
2002 count  272.000000   272.000000      272.000000
     mean   136.500000    40.918246       16.048638
     std     78.663842     9.204576       13.624337
     min      1.000000     4.920156        0.182643
     25%     68.750000    34.457467        5.395294
     50%    136.500000    41.258953       12.975101
     75%    204.250000    47.633932       22.841404
     max    272.000000    62.841526       86.946230
2008 count  272.000000   266.000000      264.000000
     mean   136.500000    44.828998       19.682475
     std     78.663842    11.284340       19.848355
     min      1.000000    12.849322        0.112574
     25%     68.750000    36.681550        5.282958
     50%    136.500000    45.603376       12.278116
     75%    204.250000    54.248752       28.253210
     max    272.000000    67.429065       92.142013
2013 count  272.000000   271.000000      271.000000
     mean   136.500000    64.041260       19.854713
     std     78.663842   194.371884       16.754505
     min      1.000000     0.000000        0.086517
     25%     68.750000    48.015000        6.837330
     50%    136.500000    56.800000       14.821770
     75%    204.250000    61.125000       28.438590
     max    272.000000  3243.000000       78.683620

In [ ]:
mergedlist = list(set(listone + listtwo))

In [25]:
winners = df_meta.winner_party.unique().tolist()
runnerups = df_meta.runnerup_party.unique().tolist()
party_list = list(set(winners+runnerups))
party_list

['Pakistan Muslim League (J)',
 nan,
 'Jamaat-e-Islami Pakistan',
 'Pakistan Muslim League (N)',
 'Muttahidda Majlis-e-Amal Pakistan',
 'All Pakistan Muslim League',
 'National Party',
 'Mohajar Qaumi Movement Pakistan',
 'Bahawalpur National Awami Party',
 'Muttahidda Qaumi Movement',
 'Tehrik-e-Istaqlal',
 'Muttahida Qaumi Movement Pakistan',
 'Pakistan Shia Political Party',
 'Independent',
 'Balochistan National Movement',
 'National Alliance',
 'Jamiat Ulama-e-Islam Nazryati Pakistan',
 'National Peoples Party',
 'Pakistan Tehreek-e-Insaf',
 'Pakistan Muslim League (Z)',
 'Sindh Taraqi Passand Party (STP)',
 'Balochistan National Party (Awami)',
 'Pakistan Peoples Party Parliamentarians',
 'Jamhoori Wattan Party',
 'Mutthida Majlis-e-Amal Pakistan (MMA)',
 'Pakistan Muslim League(Z)',
 'Jamiat Ulma-e-Pakistan (Noorani)',
 'Indepndent',
 'Pakistan Democratic party',
 'Pakistan Peoples Party (Sherpao)',
 'Muttahida Qaumi Movement',
 'MUTAHIDA DEENI MAHAZ',
 'Jamiat Ulama-e-Islam (F)',
 'Pukhtoonkhwa Milli Awami Party',
 'Pakistan Muslim League (F)',
 'Pakistan Citizen Movement',
 'Sindh United Party',
 'Qaumi Watan Party (Sherpao)',
 'Pakistan Muslim League (Q)',
 'Awami National Party',
 'Pakistan Peoples Party (Shaheed Bhutto)',
 'Pakistan Awami Tehreek',
 'Pakistan Democratic Party',
 'Balochistan National Party',
 'Awami Jamhuri Ittehad Pakistan',
 'Awami Muslim League Pakistan',
 'Pakistan Pakhtoonkhawa Milli Awami Party']

['Muttahidda Majlis-e-Amal Pakistan',
 'Pakistan Muslim League (Q)',
 'Pakistan Muslim League (J)',
 'Pakistan Peoples Party Parliamentarians',
 'Pakistan Muslim League (N)',
 'Independent',
 'Pakistan Awami Tehreek',
 'Pakistan Shia Political Party',
 'National Alliance',
 'Pakistan Muslim League (Z)',
 'Pakistan Muslim League (F)',
 'Muttahida Qaumi Movement',
 'Mohajar Qaumi Movement Pakistan',
 'Pakistan Pakhtoonkhawa Milli Awami Party',
 'Jamhoori Wattan Party',
 'Balochistan National Party',
 'Pakistan Peoples Party (Sherpao)',
 'Indepndent',
 'Pakistan Tehreek-e-Insaf',
 'Awami National Party',
 'Mutthida Majlis-e-Amal Pakistan (MMA)',
 'National Peoples Party',
 'Muttahida Qaumi Movement Pakistan',
 'Balochistan National Party (Awami)',
 nan,
 'Awami Jamhuri Ittehad Pakistan',
 'Pakistan Muslim League(Z)',
 'Muttahidda Qaumi Movement',
 'Jamiat Ulama-e-Islam (F)',
 'Pukhtoonkhwa Milli Awami Party',
 'National Party',
 'Jamaat-e-Islami Pakistan',
 'All Pakistan Muslim League',
 'Awami Muslim League Pakistan',
 'Qaumi Watan Party (Sherpao)',
 'MUTAHIDA DEENI MAHAZ',
 'Awami National Party',
 'Pakistan Peoples Party Parliamentarians',
 'Pakistan Muslim League (J)',
 'Pakistan Muslim League (N)',
 'Independent',
 'National Alliance',
 'Pakistan Muslim League (Q)',
 'Pakistan Tehreek-e-Insaf',
 'Muttahidda Majlis-e-Amal Pakistan',
 'Pakistan Democratic party',
 'Pakistan Muslim League (F)',
 'Muttahida Qaumi Movement',
 'Pakistan Pakhtoonkhawa Milli Awami Party',
 'Balochistan National Movement',
 'Indepndent',
 'Tehrik-e-Istaqlal',
 'Pakistan Awami Tehreek',
 nan,
 'Mutthida Majlis-e-Amal Pakistan (MMA)',
 'Pakistan Democratic Party',
 'National Peoples Party',
 'Pakistan Peoples Party (Shaheed Bhutto)',
 'Muttahida Qaumi Movement Pakistan',
 'Sindh United Party',
 'National Party',
 'Pakistan Peoples Party (Sherpao)',
 'Pakistan Citizen Movement',
 'Jamiat Ulama-e-Islam (F)',
 'Bahawalpur National Awami Party',
 'Pakistan Muslim League(Z)',
 'Muttahidda Qaumi Movement',
 'Jamiat Ulma-e-Pakistan (Noorani)',
 'Sindh Taraqi Passand Party (STP)',
 'Pukhtoonkhwa Milli Awami Party',
 'Jamiat Ulama-e-Islam Nazryati Pakistan',
 'Balochistan National Party',
 'Jamaat-e-Islami Pakistan']